-- KeanUHackThis team system migration
-- Run this after the existing profiles/registrations schema.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null check (length(trim(team_name)) > 0),
  creator_id uuid not null references auth.users(id) on delete cascade,
  event_year integer not null default 2027,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id uuid primary key default gen_random_uuid(),
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (team_id, user_id),
  unique (user_id)
);

create or replace function public.enforce_team_member_limit()
returns trigger
language plpgsql
as $$
declare
  current_member_count integer;
begin
  perform 1 from public.teams where id = new.team_id for update;

  select count(*)
  into current_member_count
  from public.team_members
  where team_id = new.team_id;

  if current_member_count >= 4 then
    raise exception 'Team is full. A team can have at most 4 members.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_team_member_limit_before_insert on public.team_members;
create trigger enforce_team_member_limit_before_insert
before insert on public.team_members
for each row
execute function public.enforce_team_member_limit();

drop trigger if exists set_teams_updated_at on public.teams;
create trigger set_teams_updated_at
before update on public.teams
for each row
execute function public.set_updated_at();

alter table public.teams enable row level security;
alter table public.team_members enable row level security;

drop policy if exists "Authenticated users can read teams" on public.teams;
create policy "Authenticated users can read teams"
on public.teams
for select
to authenticated
using (true);

drop policy if exists "Users can create own teams" on public.teams;
create policy "Users can create own teams"
on public.teams
for insert
to authenticated
with check (auth.uid() = creator_id);

drop policy if exists "Team creators can update own teams" on public.teams;
create policy "Team creators can update own teams"
on public.teams
for update
to authenticated
using (auth.uid() = creator_id)
with check (auth.uid() = creator_id);

drop policy if exists "Team creators can delete own teams" on public.teams;
create policy "Team creators can delete own teams"
on public.teams
for delete
to authenticated
using (auth.uid() = creator_id);

drop policy if exists "Authenticated users can read team members" on public.team_members;
create policy "Authenticated users can read team members"
on public.team_members
for select
to authenticated
using (true);

drop policy if exists "Users can add themselves to teams" on public.team_members;
create policy "Users can add themselves to teams"
on public.team_members
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can remove themselves from teams" on public.team_members;
create policy "Users can remove themselves from teams"
on public.team_members
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Creators can remove team members" on public.team_members;
create policy "Creators can remove team members"
on public.team_members
for delete
to authenticated
using (
  exists (
    select 1
    from public.teams
    where teams.id = team_members.team_id
      and teams.creator_id = auth.uid()
  )
);
