export const SCHOOLS = [
  { n: "Kean University",                                    a: ["kean","ku","kean univ"] },
  { n: "Rutgers University – New Brunswick",                 a: ["rutgers","rutgers nb","runb","rutgers new brunswick","ru"] },
  { n: "Rutgers University – Newark",                        a: ["rutgers newark","run","rutgers-newark"] },
  { n: "Rutgers University – Camden",                        a: ["rutgers camden","ruc"] },
  { n: "New Jersey Institute of Technology",                 a: ["njit","new jersey institute","nj institute of technology"] },
  { n: "Princeton University",                               a: ["princeton","pu"] },
  { n: "Stevens Institute of Technology",                    a: ["stevens","sit","stevens tech"] },
  { n: "Montclair State University",                         a: ["montclair","msu","montclair state"] },
  { n: "Rowan University",                                   a: ["rowan","rowan univ"] },
  { n: "The College of New Jersey",                          a: ["tcnj","college of new jersey","cnj"] },
  { n: "Seton Hall University",                              a: ["seton hall","shu"] },
  { n: "William Paterson University",                        a: ["william paterson","wpu","wpunj"] },
  { n: "Fairleigh Dickinson University",                     a: ["fdu","fairleigh dickinson","fairleigh"] },
  { n: "Drew University",                                    a: ["drew"] },
  { n: "Rider University",                                   a: ["rider"] },
  { n: "Stockton University",                                a: ["stockton","richard stockton"] },
  { n: "Ramapo College of New Jersey",                       a: ["ramapo","rcnj","ramapo college"] },
  { n: "New Jersey City University",                         a: ["njcu","nj city university","njcu"] },
  { n: "Monmouth University",                                a: ["monmouth"] },
  { n: "Georgian Court University",                          a: ["georgian court","gcu"] },
  { n: "Felician University",                                a: ["felician"] },
  { n: "Centenary University",                               a: ["centenary"] },
  { n: "Bergen Community College",                           a: ["bergen","bcc","bergen cc"] },
  { n: "Essex County College",                               a: ["essex","ecc","essex county"] },
  { n: "Union County College",                               a: ["union county","ucc","union cc"] },
  { n: "Middlesex College",                                  a: ["middlesex","middlesex county"] },
  { n: "Ocean County College",                               a: ["ocean county","occ"] },
  { n: "Thomas Edison State University",                     a: ["thomas edison","tesu","tesc"] },
  { n: "New York University",                                a: ["nyu","new york university"] },
  { n: "Columbia University",                                a: ["columbia","columbia univ","cu"] },
  { n: "Cornell University",                                 a: ["cornell"] },
  { n: "University of Pennsylvania",                         a: ["upenn","penn","u of penn","u penn"] },
  { n: "Massachusetts Institute of Technology",              a: ["mit"] },
  { n: "Carnegie Mellon University",                         a: ["cmu","carnegie mellon","carnegie-mellon"] },
  { n: "Georgia Institute of Technology",                    a: ["georgia tech","gatech","gt"] },
  { n: "University of Michigan",                             a: ["umich","u of michigan","university of michigan","um"] },
  { n: "Stanford University",                                a: ["stanford"] },
  { n: "Harvard University",                                 a: ["harvard"] },
  { n: "Fordham University",                                 a: ["fordham"] },
  { n: "St. Peter's University",                             a: ["st peters","st. peters","spu"] },
  { n: "Caldwell University",                                a: ["caldwell"] },
  { n: "Bloomfield College",                                 a: ["bloomfield"] },
  { n: "Pillar College",                                     a: ["pillar"] },
  { n: "New York Institute of Technology",                   a: ["nyit","ny institute of technology"] },
  { n: "Pace University",                                    a: ["pace"] },
  { n: "Hofstra University",                                 a: ["hofstra"] },
  { n: "Adelphi University",                                 a: ["adelphi"] },
  { n: "Stony Brook University",                             a: ["stony brook","sbu","suny stony brook"] },
  { n: "University at Buffalo",                              a: ["ub","buffalo","suny buffalo","university at buffalo"] },
  { n: "Baruch College – CUNY",                              a: ["baruch","cuny baruch"] },
  { n: "City College of New York – CUNY",                    a: ["ccny","city college","cuny city"] },
  { n: "Hunter College – CUNY",                              a: ["hunter","cuny hunter"] },
  { n: "Other / Not Listed",                                 a: ["other","not listed","unlisted"] }
];

export const MAJORS = [
  // Computer & Tech
  { n: "Computer Science",                        a: ["cs","compsci","comp sci","comp science"] },
  { n: "Computer Engineering",                    a: ["ce","comp eng","cpe"] },
  { n: "Software Engineering",                    a: ["swe","se","software eng"] },
  { n: "Information Technology",                  a: ["it","info tech","infotech"] },
  { n: "Information Systems",                     a: ["mis","info systems","management information systems"] },
  { n: "Cybersecurity",                           a: ["cyber","infosec","info security","cyber security"] },
  { n: "Data Science",                            a: ["ds","data sci","datascience"] },
  { n: "Artificial Intelligence",                 a: ["ai","machine learning","ml","ai/ml"] },
  { n: "Game Design & Development",               a: ["game design","game dev","game development"] },
  { n: "Web Development",                         a: ["web dev","webdev","web design"] },
  { n: "Computer Information Systems",            a: ["cis"] },
  { n: "Network & Communications Technology",     a: ["networking","nct","networks"] },
  // Engineering
  { n: "Electrical Engineering",                  a: ["ee","elec eng","electrical"] },
  { n: "Mechanical Engineering",                  a: ["me","mech eng","mechanical"] },
  { n: "Civil Engineering",                       a: ["civil","cive"] },
  { n: "Biomedical Engineering",                  a: ["bme","biomedical","biomed eng"] },
  { n: "Chemical Engineering",                    a: ["che","chem eng","chemical"] },
  { n: "Industrial Engineering",                  a: ["ie","industrial","industrial eng"] },
  { n: "Environmental Engineering",               a: ["env eng","environmental"] },
  // Business
  { n: "Business Administration",                 a: ["business","biz","ba","business admin"] },
  { n: "Finance",                                 a: ["fin","finance"] },
  { n: "Marketing",                               a: ["mkt","marketing"] },
  { n: "Accounting",                              a: ["acct","accounting"] },
  { n: "Economics",                               a: ["econ","economics"] },
  { n: "Entrepreneurship",                        a: ["entrepreneur","entrepreneurship"] },
  { n: "Management",                              a: ["mgmt","management"] },
  { n: "Supply Chain & Logistics",                a: ["supply chain","logistics","scm"] },
  // Science
  { n: "Biology",                                 a: ["bio","biol","biological sciences"] },
  { n: "Chemistry",                               a: ["chem","chemistry"] },
  { n: "Physics",                                 a: ["phys","physics"] },
  { n: "Mathematics",                             a: ["math","maths","mathematics"] },
  { n: "Statistics",                              a: ["stats","stat","statistics"] },
  { n: "Environmental Science",                   a: ["env sci","enviro","envsci"] },
  { n: "Neuroscience",                            a: ["neuro","neuroscience"] },
  { n: "Biochemistry",                            a: ["biochem","biochemistry"] },
  // Healthcare
  { n: "Nursing",                                 a: ["rn","bsn","nursing"] },
  { n: "Pre-Medicine",                            a: ["premed","pre med","pre-med","pre medicine"] },
  { n: "Public Health",                           a: ["public health","ph"] },
  { n: "Health Information Management",           a: ["him","health informatics","health info"] },
  // Liberal Arts & Social Sciences
  { n: "Psychology",                              a: ["psych","psyc","psychology"] },
  { n: "Political Science",                       a: ["poli sci","polisci","political science","pols"] },
  { n: "Sociology",                               a: ["soc","sociology"] },
  { n: "Communications",                          a: ["comm","comms","communications"] },
  { n: "Journalism",                              a: ["journalism","journ"] },
  { n: "English",                                 a: ["english","english lit"] },
  { n: "History",                                 a: ["hist","history"] },
  { n: "Criminal Justice",                        a: ["cj","criminal justice","criminology"] },
  { n: "Social Work",                             a: ["social work","sw"] },
  // Arts & Design
  { n: "Graphic Design",                          a: ["graphic design","gd","design"] },
  { n: "Digital Media",                           a: ["digital media","dm","media"] },
  { n: "Animation & Illustration",                a: ["animation","illustration","ani"] },
  { n: "Architecture",                            a: ["arch","architecture"] },
  { n: "Music Technology",                        a: ["music tech","music technology"] },
  { n: "Fine Arts",                               a: ["art","fine arts","studio art"] },
  // Education
  { n: "Education",                               a: ["edu","education","teaching"] },
  { n: "Special Education",                       a: ["spec ed","special ed","sped"] },
  // Catch-all
  { n: "Other / Undeclared",                      a: ["other","undeclared","undecided","tbd"] }
];
